{
    "version": "12.0.1.0.0",
    "name": "web_no_swipe",
    "summary": "Swipe in v12 is broken on resize. Make it a no-op.",
    "category": "Hidden",
    "images": [],
    "application": False,
    "author": "Glodo",
    "website": "https://www.glodo.uk/",
    "license": "Other proprietary",
    "depends": ["web"],
    "external_dependencies": {"python": [], "bin": []},
    "data": ["views/templates.xml"],
    "qweb": [],
    "demo": [],
    "post_load": None,
    "pre_init_hook": None,
    "post_init_hook": None,
    "uninstall_hook": None,
    "auto_install": False,
    "installable": True,
    "license": "LGPL-3",
}
